import Footer from '@/components/footer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Noto_Sans } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

const noto = Noto_Sans({
  weight:['100','200','300','400','500','600','700','800'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: 'Er. Sujan Kumal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Header/>
        {/* {children} */}

        <Footer/>
      </body>
    </html>
  )
}
